const ALLOWED=new Set(["image/jpeg","image/png","image/gif","image/webp","image/avif","image/svg+xml"]);
const json=(d,s=200)=>new Response(JSON.stringify(d),{status:s,headers:{"content-type":"application/json;charset=utf-8"}});
const ok=(r,e)=>!!e.ADMIN_KEY&&r.headers.get("x-admin-key")===e.ADMIN_KEY;
const gh=(e,p="")=>`https://api.github.com/repos/${e.GITHUB_OWNER}/${e.GITHUB_REPO}/contents/${p}`;
const raw=(e,p)=>`https://raw.githubusercontent.com/${e.GITHUB_OWNER}/${e.GITHUB_REPO}/${encodeURIComponent(e.GITHUB_BRANCH)}/${p.split("/").map(encodeURIComponent).join("/")}`;
async function api(e,u,o={}){return fetch(u,{...o,headers:{Accept:"application/vnd.github+json",Authorization:`Bearer ${e.GITHUB_TOKEN},`.slice(0,-1),"X-GitHub-Api-Version":"2022-11-28",...(o.headers||{})}})}
const ext=t=>({"image/jpeg":"jpg","image/png":"png","image/gif":"gif","image/webp":"webp","image/avif":"avif","image/svg+xml":"svg"})[t]||"bin";
function name(t){const b=new Uint8Array(10);crypto.getRandomValues(b);return `${Date.now()}-${[...b].map(x=>x.toString(16).padStart(2,"0")).join("")}.${ext(t)}`}
export default {async fetch(r,e){const u=new URL(r.url);if(!u.pathname.startsWith("/api/")){const response=await e.ASSETS.fetch(r);const headers=new Headers(response.headers);headers.set("Cache-Control","no-store,no-cache,must-revalidate,proxy-revalidate");return new Response(response.body,{status:response.status,statusText:response.statusText,headers});}if(!e.GITHUB_TOKEN||!e.ADMIN_KEY)return json({error:"Worker secrets are incomplete"},500);if(!ok(r,e))return json({error:"Unauthorized"},401);try{
if(u.pathname==="/api/config"&&r.method==="GET")return json({maxFileMB:Number(e.MAX_FILE_MB||10)});
if(u.pathname==="/api/upload"&&r.method==="POST"){const f=await r.formData(),im=f.get("image");if(!im||typeof im.arrayBuffer!=="function")return json({error:"请选择图片"},400);if(!ALLOWED.has(im.type))return json({error:"不支持的图片格式"},415);if(im.size>Number(e.MAX_FILE_MB||10)*1048576)return json({error:`图片不能超过 ${e.MAX_FILE_MB||10} MB`},413);const p=`${String(e.GITHUB_PATH||"images").replace(/^\/+|\/+$/g,"")}/${name(im.type)}`;const bytes=new Uint8Array(await im.arrayBuffer());let bin="";for(let i=0;i<bytes.length;i+=32768)bin+=String.fromCharCode(...bytes.subarray(i,i+32768));const rr=await api(e,gh(e,p),{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:`upload ${p.split("/").pop()}`,content:btoa(bin),branch:e.GITHUB_BRANCH})});const d=await rr.json();if(!rr.ok)return json({error:d.message||"GitHub 上传失败"},rr.status);const x=raw(e,p);return json({name:p.split("/").pop(),path:p,url:x,markdown:`![${p.split("/").pop()}](${x})`});}
if(u.pathname==="/api/list"&&r.method==="GET"){const p=String(e.GITHUB_PATH||"images").replace(/^\/+|\/+$/g,"");const rr=await api(e,gh(e,p)+`?ref=${encodeURIComponent(e.GITHUB_BRANCH)}`);const d=await rr.json();if(!rr.ok)return json({error:d.message||"读取 GitHub 失败"},rr.status);return json(Array.isArray(d)?d.filter(x=>x.type==="file").reverse().map(x=>({name:x.name,path:x.path,url:raw(e,x.path),sha:x.sha})):[]);}
if(u.pathname==="/api/delete"&&r.method==="DELETE"){const b=await r.json();if(!b?.path||!b?.sha)return json({error:"缺少 path 或 sha"},400);const rr=await api(e,gh(e,b.path),{method:"DELETE",headers:{"Content-Type":"application/json"},body:JSON.stringify({message:`delete ${b.path}`,sha:b.sha,branch:e.GITHUB_BRANCH})});const d=await rr.json();if(!rr.ok)return json({error:d.message||"删除失败"},rr.status);return json({ok:true});}
return json({error:"Not Found"},404);}catch(x){return json({error:x?.message||"服务器错误"},500)}}};
